schemaVersion: "2.0.0"
metadataTest:
  cmd: ["bash"]
  user: "1000:1000"
commandTests:
  - name: clang
    command: "clang++"
    args: ["--version"]
    exitCode: 0
  - name: cmake
    command: "cmake"
    args: ["--version"]
    exitCode: 0
  - name: ninja
    command: "ninja"
    args: ["--version"]
    exitCode: 0
  - name: git
    command: "git"
    args: ["--version"]
    exitCode: 0
  - name: "no setuid or setgid files"
    command: "bash"
    args:
      - "-c"
      - "! find / -xdev -type f -perm -4000 -print | grep -q . && ! find / -xdev -type f -perm -2000 -print | grep -q ."
