#!/usr/bin/env bash
# Compile a smoke TU that includes a public header from LIBRARY_PATH when one
# exists (MOBILE-MECH-001). Falls back to <cstdio> for repos without include/.
set -euo pipefail

CXX="${1:?compiler required}"
OUT="${2:?output path required}"
shift 2
# Remaining args are extra compiler flags (SDK sysroot, -arch, …).

LIBRARY_PATH="${LIBRARY_PATH:-.}"
ROOT="$(cd "${LIBRARY_PATH}" && pwd)"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GEN="${RUNNER_TEMP:-/tmp}/mobile-smoke-tu.cpp"
mkdir -p "$(dirname "${OUT}")" "$(dirname "${GEN}")"

header=""
if [[ -d "${ROOT}/include" ]]; then
  header="$(find "${ROOT}/include" -type f \( -name '*.hpp' -o -name '*.h' \) | sort | head -1 || true)"
fi

{
  echo "// Generated by cppdevops scripts/mobile-smoke/compile.sh"
  if [[ -n "${header}" ]]; then
    rel="${header#"${ROOT}/include/"}"
    echo "#include <${rel}>"
  fi
  echo "#include <cstdio>"
  echo "int main() { std::puts(\"cppdevops mobile smoke ok\"); return 0; }"
} > "${GEN}"

if [[ -n "${header}" ]]; then
  echo "including public header ${header#"${ROOT}/"}"
  extras=(-I "${ROOT}/include")
else
  echo "notice: no public header under ${ROOT}/include — compiling <cstdio> only"
  extras=()
fi

"${CXX}" -stdlib=libc++ -std=c++20 "${extras[@]}" "$@" -o "${OUT}" "${GEN}"
file "${OUT}"
